// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZbYt_E0cwSy9B7M7bQKPl_rHUA0C1bZA',
    appId: '1:509740150836:web:26a2445eafa58584cc1a61',
    messagingSenderId: '509740150836',
    projectId: 'nearby-pay-nashit-27102710',
    authDomain: 'nearby-pay-nashit-27102710.firebaseapp.com',
    storageBucket: 'nearby-pay-nashit-27102710.firebasestorage.app',
    measurementId: 'G-0L1KLH6KKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_av6eIn7vNuJLh1BrKtA3lWl3PdFY7g',
    appId: '1:509740150836:android:55ca539991a3d863cc1a61',
    messagingSenderId: '509740150836',
    projectId: 'nearby-pay-nashit-27102710',
    storageBucket: 'nearby-pay-nashit-27102710.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZbYt_E0cwSy9B7M7bQKPl_rHUA0C1bZA',
    appId: '1:509740150836:web:86da4dfdac3e855ccc1a61',
    messagingSenderId: '509740150836',
    projectId: 'nearby-pay-nashit-27102710',
    authDomain: 'nearby-pay-nashit-27102710.firebaseapp.com',
    storageBucket: 'nearby-pay-nashit-27102710.firebasestorage.app',
    measurementId: 'G-Z1LZQP5JE3',
  );
}
